version: '3'
services:
  webdav-express-server:
    container_name: webdav-express-server
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: bananaacid/webdav-express-server