version: '3'
services:
  webdav-express-server:
    container_name: webdav-express-server

    image: bananaacid/webdav-express-server:v1
    environment:
      # log messages
      - DEBUG=*
      # session secret
      - SECRET=sa7h8g6fZGUBHKJNuh76g8ziuhGZ/ubdf#
      # - PROTECT= boolean -> 'false' -> enable password protection, enables admin and config/users.ts
      # - USERNAME= string -> 'username' -> admin user username
      # - PASSWORD= string -> 'password' -> admin user password
      # - REALM= string -> 'Protected Area' -> login title
      # - PORT= number -> '80'
    ports:
      - '1900:80'
    expose:
      - '1900'
    volumes:
      # the config folder
      - ./test/config:/home/node/config
      # the upload folder
      - ./test/upload:/home/node/upload

    working_dir: /home/node

    restart: unless-stopped
